export enum SaleTypeEnum {
  ESTOQUE_PROPRIO = 'ESTOQUE_PROPRIO',
  VENDA_DIRETA = 'VENDA_DIRETA',
  PRODUCAO_PROPRIA = 'PRODUCAO_PROPRIA',
  VENDA_PECA = 'VENDA_PECA',
  SERVICO_OFICINA = 'SERVICO_OFICINA',
  FI_CONSORCIO = 'FI_CONSORCIO',
  FI_FINANCIAMENTO = 'FI_FINANCIAMENTO',
  FI_SEGURO = 'FI_SEGURO',
}
