export const CST_ICMS_DATA = [
  { code: '00', description: 'Tributada integralmente', categoria: 'TRIBUTADO' },
  { code: '10', description: 'Tributada e com cobrança do ICMS por substituição tributária', categoria: 'TRIBUTADO_ST' },
  { code: '20', description: 'Com redução de base de cálculo', categoria: 'TRIBUTADO_REDUCAO' },
  { code: '30', description: 'Isenta ou não tributada e com cobrança do ICMS por ST', categoria: 'ISENTO_ST' },
  { code: '40', description: 'Isenta', categoria: 'ISENTO' },
  { code: '41', description: 'Não tributada', categoria: 'NAO_TRIBUTADO' },
  { code: '50', description: 'Suspensão', categoria: 'SUSPENSAO' },
  { code: '51', description: 'Diferimento', categoria: 'DIFERIMENTO' },
  { code: '60', description: 'ICMS cobrado anteriormente por substituição tributária', categoria: 'ST_RECOLHIDO' },
  { code: '70', description: 'Com redução de base de cálculo e cobrança do ICMS por ST', categoria: 'REDUCAO_ST' },
  { code: '90', description: 'Outros', categoria: 'OUTROS' },
];

export const CSOSN_DATA = [
  { code: '101', description: 'Tributada pelo Simples Nacional com permissão de crédito' },
  { code: '102', description: 'Tributada pelo Simples Nacional sem permissão de crédito' },
  { code: '103', description: 'Isenção do ICMS no Simples Nacional para faixa de receita bruta' },
  { code: '201', description: 'Tributada pelo Simples Nacional com permissão de crédito e com cobrança do ICMS por ST' },
  { code: '202', description: 'Tributada pelo Simples Nacional sem permissão de crédito e com cobrança do ICMS por ST' },
  { code: '203', description: 'Isenção do ICMS no SN para faixa de receita bruta e com cobrança do ICMS por ST' },
  { code: '300', description: 'Imune' },
  { code: '400', description: 'Não tributada pelo Simples Nacional' },
  { code: '500', description: 'ICMS cobrado anteriormente por ST ou por antecipação' },
  { code: '900', description: 'Outros' },
];

export const CST_IPI_DATA = [
  { code: '00', description: 'Entrada com recuperação de crédito', tipo: 'ENTRADA' },
  { code: '01', description: 'Entrada tributada com alíquota zero', tipo: 'ENTRADA' },
  { code: '02', description: 'Entrada isenta', tipo: 'ENTRADA' },
  { code: '03', description: 'Entrada não tributada', tipo: 'ENTRADA' },
  { code: '04', description: 'Entrada imune', tipo: 'ENTRADA' },
  { code: '05', description: 'Entrada com suspensão', tipo: 'ENTRADA' },
  { code: '49', description: 'Outras entradas', tipo: 'ENTRADA' },
  { code: '50', description: 'Saída tributada', tipo: 'SAIDA' },
  { code: '51', description: 'Saída tributável com alíquota zero', tipo: 'SAIDA' },
  { code: '52', description: 'Saída isenta', tipo: 'SAIDA' },
  { code: '53', description: 'Saída não tributada', tipo: 'SAIDA' },
  { code: '54', description: 'Saída imune', tipo: 'SAIDA' },
  { code: '55', description: 'Saída com suspensão', tipo: 'SAIDA' },
  { code: '99', description: 'Outras saídas', tipo: 'SAIDA' },
];

export const CST_PIS_COFINS_DATA = [
  { code: '01', description: 'Op. tributável - BC = valor da operação, alíquota normal', tipo: 'SAIDA', regime: 'NAO_CUMULATIVO' },
  { code: '02', description: 'Op. tributável - BC = valor da operação, alíquota diferenciada', tipo: 'SAIDA', regime: 'NAO_CUMULATIVO' },
  { code: '03', description: 'Op. tributável - BC = quantidade vendida x alíquota por unidade', tipo: 'SAIDA', regime: 'NAO_CUMULATIVO' },
  { code: '04', description: 'Operação tributável - tributação monofásica (alíquota zero)', tipo: 'SAIDA', regime: 'AMBOS' },
  { code: '05', description: 'Operação tributável por substituição tributária', tipo: 'SAIDA', regime: 'NAO_CUMULATIVO' },
  { code: '06', description: 'Operação tributável a alíquota zero', tipo: 'SAIDA', regime: 'NAO_CUMULATIVO' },
  { code: '07', description: 'Operação isenta da contribuição', tipo: 'SAIDA', regime: 'AMBOS' },
  { code: '08', description: 'Operação sem incidência da contribuição', tipo: 'SAIDA', regime: 'AMBOS' },
  { code: '09', description: 'Operação com suspensão da contribuição', tipo: 'SAIDA', regime: 'AMBOS' },
  { code: '49', description: 'Outras saídas', tipo: 'SAIDA', regime: 'AMBOS' },
  { code: '50', description: 'Op. com direito a crédito - vinculada a receitas tributadas', tipo: 'ENTRADA', regime: 'NAO_CUMULATIVO' },
  { code: '51', description: 'Op. com direito a crédito - vinculada a receitas não-tributadas', tipo: 'ENTRADA', regime: 'NAO_CUMULATIVO' },
  { code: '52', description: 'Op. com direito a crédito - vinculada a receitas de exportação', tipo: 'ENTRADA', regime: 'NAO_CUMULATIVO' },
  { code: '53', description: 'Op. com direito a crédito - vinculada a rec. tributadas e não-tributadas', tipo: 'ENTRADA', regime: 'NAO_CUMULATIVO' },
  { code: '54', description: 'Op. com direito a crédito - vinculada a rec. tributadas e de exportação', tipo: 'ENTRADA', regime: 'NAO_CUMULATIVO' },
  { code: '55', description: 'Op. com direito a crédito - vinculada a rec. não-tributadas e de exportação', tipo: 'ENTRADA', regime: 'NAO_CUMULATIVO' },
  { code: '56', description: 'Op. com direito a crédito - vinculada a rec. tributadas, não-tributadas e exportação', tipo: 'ENTRADA', regime: 'NAO_CUMULATIVO' },
  { code: '60', description: 'Crédito presumido - op. de aquisição vinculada a receitas tributadas', tipo: 'ENTRADA', regime: 'NAO_CUMULATIVO' },
  { code: '70', description: 'Operação de aquisição sem direito a crédito', tipo: 'ENTRADA', regime: 'NAO_CUMULATIVO' },
  { code: '71', description: 'Operação de aquisição com isenção', tipo: 'ENTRADA', regime: 'NAO_CUMULATIVO' },
  { code: '72', description: 'Operação de aquisição com suspensão', tipo: 'ENTRADA', regime: 'NAO_CUMULATIVO' },
  { code: '73', description: 'Operação de aquisição a alíquota zero', tipo: 'ENTRADA', regime: 'NAO_CUMULATIVO' },
  { code: '74', description: 'Operação de aquisição sem incidência', tipo: 'ENTRADA', regime: 'NAO_CUMULATIVO' },
  { code: '75', description: 'Operação de aquisição por substituição tributária', tipo: 'ENTRADA', regime: 'NAO_CUMULATIVO' },
  { code: '98', description: 'Outras operações de entrada', tipo: 'ENTRADA', regime: 'AMBOS' },
  { code: '99', description: 'Outras operações', tipo: 'AMBOS', regime: 'AMBOS' },
];

export const BANCOS_DATA = [
  { code: '001', ispb: '00000000', name: 'BANCO DO BRASIL S.A.', shortName: 'BB', tipo: 'BANCO_MULTIPLO' },
  { code: '033', ispb: '90400888', name: 'BANCO SANTANDER (BRASIL) S.A.', shortName: 'SANTANDER', tipo: 'BANCO_MULTIPLO' },
  { code: '041', ispb: '92702067', name: 'BANCO DO ESTADO DO RIO GRANDE DO SUL S.A.', shortName: 'BANRISUL', tipo: 'BANCO_MULTIPLO' },
  { code: '070', ispb: '00000208', name: 'BRB - BANCO DE BRASILIA S.A.', shortName: 'BRB', tipo: 'BANCO_MULTIPLO' },
  { code: '077', ispb: '00416968', name: 'BANCO INTER S.A.', shortName: 'INTER', tipo: 'BANCO_MULTIPLO' },
  { code: '104', ispb: '00360305', name: 'CAIXA ECONOMICA FEDERAL', shortName: 'CEF', tipo: 'CAIXA_ECONOMICA' },
  { code: '212', ispb: '92894922', name: 'BANCO ORIGINAL S.A.', shortName: 'ORIGINAL', tipo: 'BANCO_MULTIPLO' },
  { code: '237', ispb: '60746948', name: 'BANCO BRADESCO S.A.', shortName: 'BRADESCO', tipo: 'BANCO_MULTIPLO' },
  { code: '260', ispb: '18236120', name: 'NU PAGAMENTOS S.A. - INSTITUIÇÃO DE PAGAMENTO', shortName: 'NUBANK', tipo: 'INSTITUICAO_PAGAMENTO' },
  { code: '336', ispb: '92702067', name: 'BANCO C6 S.A.', shortName: 'C6', tipo: 'BANCO_MULTIPLO' },
  { code: '341', ispb: '60701190', name: 'ITAÚ UNIBANCO S.A.', shortName: 'ITAU', tipo: 'BANCO_MULTIPLO' },
  { code: '380', ispb: '09516419', name: 'PICPAY SERVICOS S.A.', shortName: 'PICPAY', tipo: 'INSTITUICAO_PAGAMENTO' },
  { code: '422', ispb: '58160789', name: 'BANCO SAFRA S.A.', shortName: 'SAFRA', tipo: 'BANCO_MULTIPLO' },
  { code: '748', ispb: '01181521', name: 'BANCO COOPERATIVO SICREDI S.A.', shortName: 'SICREDI', tipo: 'BANCO_COOPERATIVO' },
  { code: '756', ispb: '02038232', name: 'BANCO COOPERATIVO DO BRASIL S.A. - BANCOOB', shortName: 'SICOOB', tipo: 'BANCO_COOPERATIVO' },
];

export const PAISES_DATA = [
  { code: '1058', iso2: 'BR', iso3: 'BRA', name: 'BRASIL', nameEn: 'BRAZIL' },
  { code: '0158', iso2: 'DE', iso3: 'DEU', name: 'ALEMANHA', nameEn: 'GERMANY' },
  { code: '0175', iso2: 'AR', iso3: 'ARG', name: 'ARGENTINA', nameEn: 'ARGENTINA' },
  { code: '0351', iso2: 'CN', iso3: 'CHN', name: 'CHINA', nameEn: 'CHINA' },
  { code: '0531', iso2: 'ES', iso3: 'ESP', name: 'ESPANHA', nameEn: 'SPAIN' },
  { code: '0558', iso2: 'US', iso3: 'USA', name: 'ESTADOS UNIDOS DA AMERICA', nameEn: 'UNITED STATES' },
  { code: '0586', iso2: 'FR', iso3: 'FRA', name: 'FRANCA', nameEn: 'FRANCE' },
  { code: '0643', iso2: 'GB', iso3: 'GBR', name: 'GRA BRETANHA', nameEn: 'UNITED KINGDOM' },
  { code: '0750', iso2: 'IN', iso3: 'IND', name: 'INDIA', nameEn: 'INDIA' },
  { code: '0845', iso2: 'IT', iso3: 'ITA', name: 'ITALIA', nameEn: 'ITALY' },
  { code: '0855', iso2: 'JP', iso3: 'JPN', name: 'JAPAO', nameEn: 'JAPAN' },
  { code: '1112', iso2: 'PY', iso3: 'PRY', name: 'PARAGUAI', nameEn: 'PARAGUAY' },
  { code: '1140', iso2: 'PE', iso3: 'PER', name: 'PERU', nameEn: 'PERU' },
  { code: '1175', iso2: 'PT', iso3: 'PRT', name: 'PORTUGAL', nameEn: 'PORTUGAL' },
  { code: '1310', iso2: 'SE', iso3: 'SWE', name: 'SUECIA', nameEn: 'SWEDEN' },
  { code: '1330', iso2: 'CH', iso3: 'CHE', name: 'SUICA', nameEn: 'SWITZERLAND' },
  { code: '1406', iso2: 'UY', iso3: 'URY', name: 'URUGUAI', nameEn: 'URUGUAY' },
  { code: '9999', iso2: 'EX', iso3: 'EXT', name: 'EXTERIOR', nameEn: 'EXTERIOR' },
];
